### ISSUE TITLE
Fix File Structure

### ISSUE THREAD

**Issue by jamestewartjr** [Moniarchy/ProjectSZPH#15]
I believe the current file structure needs to be improved. There are two package jsons, two yarn.locks, and no root directory package.json.  Dependencies need to be centralized.

Which one am I to use? @Moniarchy

**Comment by Moniarchy** [comment]
In the projects I have worked on with the need for a separate back and front end, we also have two separate package.jsons and/or yarn.locks. I haven't yet figured a way around this, I need to do some research on this. I think Trossello probably has a good set up, so I'm going to look at their file structure tonight and come up with something for tomorrow. Is this keeping you from setting up testing?

**Comment by jamestewartjr** [comment]
Oh I see. I suggest we delete the back-end folder (I.e express generator ) and manually add express. In the root project folder we can build it there. 

I can issue a PR tomorrow if you want.

**Comment by Moniarchy** [comment]
I'm fine with this. Another thing we could do is delete the back end entirely for now until we're actually needing to route to and from the database. It gives us time to look at other projects to see how they've encountered and dealt with this.

**Comment by jamestewartjr** [comment]
I like your idea. I'll make the changes tomorrow for you to review before
the  end of the day.

**Comment by Moniarchy** [comment]
Thanks so much. I'll take a preliminary look at your other PR too.
