### ISSUE TITLE
Create initial code repo

### ISSUE THREAD

**Issue by jamestewartjr** [Moniarchy/ProjectSZPH#4]
As a developer, I need initial code to get started with all dependencies included.

-[X] React
-[ ] Redux
-[X]Node
-[ ]MongoDB
-[X]Express
-[X]Yarn
-[X]Webpack (Babel)
-[ ]Testing Suite
-[ ]Sass
-[ ]Heroku

**Comment by Moniarchy** [comment]
Before the end of this week I'll try to write out instructions (for my learning and so others can more easily contribute) for setting up their environment, including installing yarn and initializing a SZPH database, if we decide that we want one this early. I'm pretty sure that webpack comes with the react app generator, which means that we should be able to use SASS now.

Deploying to Heroku is something I haven't yet successfully done.
